//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frep2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("frep2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border = 1 &gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt; Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds -%}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{ cur [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_1_Default_Template {
            get {
                return ResourceManager.GetString("Query_1_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_10_Default_Template {
            get {
                return ResourceManager.GetString("Query_10_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_11_Default_Template {
            get {
                return ResourceManager.GetString("Query_11_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			
        ///			&lt;th&gt;Value Research Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_12_Default_Template {
            get {
                return ResourceManager.GetString("Query_12_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund.note1}}&lt;/td&gt;
        ///			&lt;td&gt;{{currentFund.fundName} [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_13_Default_Template {
            get {
                return ResourceManager.GetString("Query_13_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Overall Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;Highest Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///		 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_14_Default_Template {
            get {
                return ResourceManager.GetString("Query_14_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			
        ///			&lt;th&gt;Value Research Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_15_Default_Template {
            get {
                return ResourceManager.GetString("Query_15_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund.note1}}&lt;/td&gt;
        ///			&lt;td&gt;{{currentFund.fundName} [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_16_Default_Template {
            get {
                return ResourceManager.GetString("Query_16_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Overall Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;Highest Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///		 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_17_Default_Template {
            get {
                return ResourceManager.GetString("Query_17_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_18_Default_Template {
            get {
                return ResourceManager.GetString("Query_18_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_19_Default_Template {
            get {
                return ResourceManager.GetString("Query_19_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_2_Default_Template {
            get {
                return ResourceManager.GetString("Query_2_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_20_Default_Template {
            get {
                return ResourceManager.GetString("Query_20_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_3_Default_Template {
            get {
                return ResourceManager.GetString("Query_3_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_4_Default_Template {
            get {
                return ResourceManager.GetString("Query_4_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			
        ///			&lt;th&gt;Value Research Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_5_Default_Template {
            get {
                return ResourceManager.GetString("Query_5_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund.note1}}&lt;/td&gt;
        ///			&lt;td&gt;{{currentFund.fundName} [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_6_Default_Template {
            get {
                return ResourceManager.GetString("Query_6_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Overall Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;Highest Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///		 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_7_Default_Template {
            get {
                return ResourceManager.GetString("Query_7_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_8_Default_Template {
            get {
                return ResourceManager.GetString("Query_8_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_9_Default_Template {
            get {
                return ResourceManager.GetString("Query_9_Default_Template", resourceCulture);
            }
        }
    }
}
