//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frep2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("frep2.Properties.Resources", System.Reflection.Assembly.GetEntryAssembly());
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;assign&apos; tag - Valid syntax: assign [var] = [source].
        /// </summary>
        internal static string AssignTagSyntaxException {
            get {
                return ResourceManager.GetString("AssignTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error - This liquid context does not allow includes.
        /// </summary>
        internal static string BlankFileSystemDoesNotAllowIncludesException {
            get {
                return ResourceManager.GetString("BlankFileSystemDoesNotAllowIncludesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liquid Error - Block &apos;{0}&apos; already defined.
        /// </summary>
        internal static string BlockTagAlreadyDefinedException {
            get {
                return ResourceManager.GetString("BlockTagAlreadyDefinedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} tag does not expect else tag.
        /// </summary>
        internal static string BlockTagNoElseException {
            get {
                return ResourceManager.GetString("BlockTagNoElseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;end&apos; is not a valid delimiter for {0} tags. Use {1}.
        /// </summary>
        internal static string BlockTagNoEndException {
            get {
                return ResourceManager.GetString("BlockTagNoEndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} tag was never closed.
        /// </summary>
        internal static string BlockTagNotClosedException {
            get {
                return ResourceManager.GetString("BlockTagNotClosedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag &apos;{0}&apos; was not properly terminated with regexp: {1}.
        /// </summary>
        internal static string BlockTagNotTerminatedException {
            get {
                return ResourceManager.GetString("BlockTagNotTerminatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;block&apos; tag - Valid syntax: block [name].
        /// </summary>
        internal static string BlockTagSyntaxException {
            get {
                return ResourceManager.GetString("BlockTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown tag &apos;{0}&apos;.
        /// </summary>
        internal static string BlockUnknownTagException {
            get {
                return ResourceManager.GetString("BlockUnknownTagException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Variable &apos;{0}&apos; was not properly terminated with regexp: {1}.
        /// </summary>
        internal static string BlockVariableNotTerminatedException {
            get {
                return ResourceManager.GetString("BlockVariableNotTerminatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;capture&apos; tag - Valid syntax: capture [var].
        /// </summary>
        internal static string CaptureTagSyntaxException {
            get {
                return ResourceManager.GetString("CaptureTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;case&apos; tag - Valid else condition: {{% else %}} (no parameters).
        /// </summary>
        internal static string CaseTagElseSyntaxException {
            get {
                return ResourceManager.GetString("CaseTagElseSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;case&apos; tag - Valid syntax: case [condition].
        /// </summary>
        internal static string CaseTagSyntaxException {
            get {
                return ResourceManager.GetString("CaseTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;case&apos; tag - Valid when condition: {{% when [condition] [or condition2...] %}}.
        /// </summary>
        internal static string CaseTagWhenSyntaxException {
            get {
                return ResourceManager.GetString("CaseTagWhenSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown operator {0}.
        /// </summary>
        internal static string ConditionUnknownOperatorException {
            get {
                return ResourceManager.GetString("ConditionUnknownOperatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liquid error: {0}.
        /// </summary>
        internal static string ContextLiquidError {
            get {
                return ResourceManager.GetString("ContextLiquidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liquid syntax error: {0}.
        /// </summary>
        internal static string ContextLiquidSyntaxError {
            get {
                return ResourceManager.GetString("ContextLiquidSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object &apos;{0}&apos; is invalid because it is neither a built-in type nor implements ILiquidizable.
        /// </summary>
        internal static string ContextObjectInvalidException {
            get {
                return ResourceManager.GetString("ContextObjectInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nesting too deep.
        /// </summary>
        internal static string ContextStackException {
            get {
                return ResourceManager.GetString("ContextStackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;cycle&apos; tag - Valid syntax: cycle [name :] var [, var2, var3 ...].
        /// </summary>
        internal static string CycleTagSyntaxException {
            get {
                return ResourceManager.GetString("CycleTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing property. Did you mean &apos;{0}&apos;?.
        /// </summary>
        internal static string DropWrongNamingConventionMessage {
            get {
                return ResourceManager.GetString("DropWrongNamingConventionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liquid Error - &apos;extends&apos; tag can be used only once.
        /// </summary>
        internal static string ExtendsTagCanBeUsedOneException {
            get {
                return ResourceManager.GetString("ExtendsTagCanBeUsedOneException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liquid Error - &apos;extends&apos; must be the first tag in an extending template.
        /// </summary>
        internal static string ExtendsTagMustBeFirstTagException {
            get {
                return ResourceManager.GetString("ExtendsTagMustBeFirstTagException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;extends&apos; tag - Valid syntax: extends [template].
        /// </summary>
        internal static string ExtendsTagSyntaxException {
            get {
                return ResourceManager.GetString("ExtendsTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liquid Error - Only &apos;comment&apos; and &apos;block&apos; tags are allowed in an extending template.
        /// </summary>
        internal static string ExtendsTagUnallowedTagsException {
            get {
                return ResourceManager.GetString("ExtendsTagUnallowedTagsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;for&apos; tag - Valid syntax: for [item] in [collection].
        /// </summary>
        internal static string ForTagSyntaxException {
            get {
                return ResourceManager.GetString("ForTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;if&apos; tag - Valid syntax: if [expression].
        /// </summary>
        internal static string IfTagSyntaxException {
            get {
                return ResourceManager.GetString("IfTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;if&apos; tag - max 500 conditions are allowed.
        /// </summary>
        internal static string IfTagTooMuchConditionsException {
            get {
                return ResourceManager.GetString("IfTagTooMuchConditionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;include&apos; tag - Valid syntax: include [template].
        /// </summary>
        internal static string IncludeTagSyntaxException {
            get {
                return ResourceManager.GetString("IncludeTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///        &lt;h1&gt;#{{ currentFund.FundID }} &quot;{{ currentFund.fundName }}&quot;&lt;/h1&gt;
        ///        &lt;p&gt;note1 : {{ currentFund.note1 }}&lt;/p&gt;
        ///        &lt;p&gt;note2 : {{ currentFund.note2 }}&lt;/p&gt;
        ///        &lt;p&gt;note3 : {{ currentFund.note3 }}&lt;/p&gt;
        ///        &lt;p&gt;note4 : {{ currentFund.note4 }}&lt;/p&gt;
        ///        &lt;p&gt;note5 : {{ currentFund.note5 }}&lt;/p&gt;
        ///        &lt;p&gt;note6 : {{ currentFund.note6 }}&lt;/p&gt;
        ///        &lt;p&gt;note7 : {{ currentFund.note7 }}&lt;/p&gt;
        ///        &lt;p&gt;fundLaunchDate : {{ currentFund.fu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Individual_Query_Default_Template {
            get {
                return ResourceManager.GetString("Individual_Query_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error - Illegal template name &apos;{0}&apos;.
        /// </summary>
        internal static string LocalFileSystemIllegalTemplateNameException {
            get {
                return ResourceManager.GetString("LocalFileSystemIllegalTemplateNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error - Illegal template path &apos;{0}&apos;.
        /// </summary>
        internal static string LocalFileSystemIllegalTemplatePathException {
            get {
                return ResourceManager.GetString("LocalFileSystemIllegalTemplatePathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error - No such template &apos;{0}&apos;.
        /// </summary>
        internal static string LocalFileSystemTemplateNotFoundException {
            get {
                return ResourceManager.GetString("LocalFileSystemTemplateNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;p&gt;example for req4: &apos;1&apos; = &quot;{{fundCategory@1}}&quot;, &apos;5&apos; = &quot;{{fundCategory@5}}&quot;, &lt;/p&gt;
        ///	&lt;table border = 1 &gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt; Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_1_Default_Template {
            get {
                return ResourceManager.GetString("Query_1_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_10_Default_Template {
            get {
                return ResourceManager.GetString("Query_10_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_11_Default_Template {
            get {
                return ResourceManager.GetString("Query_11_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			
        ///			&lt;th&gt;Value Research Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_12_Default_Template {
            get {
                return ResourceManager.GetString("Query_12_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund.note1}}&lt;/td&gt;
        ///			&lt;td&gt;{{currentFund.fundName} [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_13_Default_Template {
            get {
                return ResourceManager.GetString("Query_13_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Overall Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;Highest Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///		 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_14_Default_Template {
            get {
                return ResourceManager.GetString("Query_14_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			
        ///			&lt;th&gt;Value Research Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_15_Default_Template {
            get {
                return ResourceManager.GetString("Query_15_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund.note1}}&lt;/td&gt;
        ///			&lt;td&gt;{{currentFund.fundName} [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_16_Default_Template {
            get {
                return ResourceManager.GetString("Query_16_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Overall Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;Highest Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///		 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_17_Default_Template {
            get {
                return ResourceManager.GetString("Query_17_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_18_Default_Template {
            get {
                return ResourceManager.GetString("Query_18_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_19_Default_Template {
            get {
                return ResourceManager.GetString("Query_19_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change LONG in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{curr [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_2_Default_Template {
            get {
                return ResourceManager.GetString("Query_2_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_20_Default_Template {
            get {
                return ResourceManager.GetString("Query_20_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;p&gt;example for req4: &apos;1&apos; = &quot;{{fundCategory@1}}&quot;, &apos;5&apos; = &quot;{{fundCategory@5}}&quot;, &lt;/p&gt;
        ///	&lt;table border = 1 &gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt; Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_21_Default_Template {
            get {
                return ResourceManager.GetString("Query_21_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_22_Default_Template {
            get {
                return ResourceManager.GetString("Query_22_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_3_Default_Template {
            get {
                return ResourceManager.GetString("Query_3_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Performance Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;% Performance Improvement&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_4_Default_Template {
            get {
                return ResourceManager.GetString("Query_4_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			
        ///			&lt;th&gt;Value Research Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_5_Default_Template {
            get {
                return ResourceManager.GetString("Query_5_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFund.note1}}&lt;/td&gt;
        ///			&lt;td&gt;{{currentFund.fundName} [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_6_Default_Template {
            get {
                return ResourceManager.GetString("Query_6_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Fund Launch Date&lt;/th&gt;
        ///			&lt;th&gt;No. Of Days Since Launch&lt;/th&gt;
        ///			&lt;th&gt;Overall Score&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Performance Improvement % Rank&lt;/th&gt;
        ///			&lt;th&gt;Highest Rating Rank&lt;/th&gt;
        ///			&lt;th&gt;NAV as of today&lt;/th&gt;
        ///		 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_7_Default_Template {
            get {
                return ResourceManager.GetString("Query_7_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_8_Default_Template {
            get {
                return ResourceManager.GetString("Query_8_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;Results for: {{fundCategory}}&lt;/h1&gt;
        ///	&lt;table border=1&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Note 1&lt;/th&gt;
        ///			&lt;th&gt;Fund Name&lt;/th&gt;
        ///			&lt;th&gt;Value Research Rating as on Today&lt;/th&gt;
        ///			&lt;th&gt;Total Bond Sales in Rs (Crores) as on 3.30pm Today&lt;/th&gt;
        ///			&lt;th&gt;Performance Score Rank&lt;/th&gt;
        ///			&lt;th&gt;Yesterday NAV&lt;/th&gt;
        ///			&lt;th&gt;Today&apos;s NAV&lt;/th&gt;
        ///			&lt;th&gt;Note 2&lt;/th&gt;
        ///			&lt;th&gt;Change in NAV&lt;/th&gt;
        ///			&lt;th&gt;% Change in NAV&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		{% for currentFund in mutualFunds %}
        ///		&lt;tr&gt;
        ///			&lt;td&gt;{{currentFu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_9_Default_Template {
            get {
                return ResourceManager.GetString("Query_9_Default_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error - Filter &apos;{0}&apos; does not have a default value for &apos;{1}&apos; and no value was supplied.
        /// </summary>
        internal static string StrainerFilterHasNoValueException {
            get {
                return ResourceManager.GetString("StrainerFilterHasNoValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error in &apos;tablerow&apos; tag - Valid syntax: tablerow [item] in [collection] cols=[number].
        /// </summary>
        internal static string TableRowTagSyntaxException {
            get {
                return ResourceManager.GetString("TableRowTagSyntaxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error - Filter &apos;{0}&apos; in &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string VariableFilterNotFoundException {
            get {
                return ResourceManager.GetString("VariableFilterNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error - Variable &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string VariableNotFoundException {
            get {
                return ResourceManager.GetString("VariableNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на key could not be found.
        /// </summary>
        internal static string WeakTableKeyNotFoundException {
            get {
                return ResourceManager.GetString("WeakTableKeyNotFoundException", resourceCulture);
            }
        }
    }
}
